name: Build certipy Windows Executable
on:
  workflow_dispatch: # This allows manual triggering
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install certipy and dependencies
        run: |
          python -m pip install --upgrade pip
          # Install certipy_windows and its dependencies
          pip install -e .
          # Install PyInstaller
          pip install pyinstaller
      - name: Build executable
        run: |
          # Create a simple entry point script
          echo 'import sys; from certipy.entry import main; sys.exit(main())' > certipy_launcher.py
          # Use this entry script for PyInstaller
          pyinstaller --onefile --name certipy_windows_amd64.exe certipy_launcher.py
      - name: Create zip file
        run: |
          Compress-Archive -Path .\\dist\\certipy_windows_amd64.exe -DestinationPath certipy_windows.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: certipy_windows
          path: certipy_windows.zip
